services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_USERNAME=newsuser
      - SPRING_DATASOURCE_PASSWORD=newspass
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_PRISMEDIA=DEBUG
      - LOGGING_FILE_NAME=/logs/application.log
    volumes:
      - ./newsdb:/workspace/app/newsdb
      - ./logs:/logs
    depends_on:
      db:
        condition: service_healthy
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=newsdb
      - POSTGRES_USER=newsuser
      - POSTGRES_PASSWORD=newspass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U newsuser -d newsdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
