# 공통 설정
spring:
  application:
    name: prismedia-scraper
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: ${LOGGING_FILE_NAME:/logs/application.log}
  level:
    root: INFO
    org.prismedia: INFO

---
# 로컬 개발 환경 설정
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:file:./newsdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: ${LOGGING_FILE_NAME:/logs/application.log}
  level:
    org.prismedia: DEBUG
    org.hibernate.SQL: DEBUG

---
# 프로덕션 환경 설정
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://db:5432/newsdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
logging:
  charset:
    console: UTF-8
    file: UTF-8
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: ${LOGGING_FILE_NAME:/logs/application.log}
  level:
    org.prismedia: DEBUG
    org.hibernate.SQL: DEBUG
